# Slicing
1. ndarray[start:end]
2. ndarray[start:]
3. ndarray[:end]

## 1. Slicing in a 2-D ndarray

In [4]:
import numpy as np
# We create a 4 x 5 ndarray that contains integers from 0 to 19
X = np.arange(20).reshape(4, 5)

# We print X
print()
print('X = \n', X)
print()

# We select all the elements that are in the 2nd through 4th rows and in the 3rd to 5th columns
# (The 1st being index 0)
Z = X[1:4,2:5]

# We print Z
print('Z = \n', Z)

# We can select the same elements as above using method 2
W = X[1:,2:5]

# We print W
print()
print('W = \n', W)

# We select all the elements that are in the 1st through 3rd rows and in the 3rd to 4th columns
Y = X[:3,2:5]

# We print Y
print()
print('Y = \n', Y)

# We select all the elements in the 3rd row
v = X[2,:]

# We print v
print()
print('v = ', v)

# We select all the elements in the 3rd column
q = X[:,2]

# We print q
print()
print('q = ', q)

# We select all the elements in the 3rd column but return a rank 2 ndarray
R = X[:,2:3]

# We print R
print()
print('R = \n', R)


X = 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]

Z = 
 [[ 7  8  9]
 [12 13 14]
 [17 18 19]]

W = 
 [[ 7  8  9]
 [12 13 14]
 [17 18 19]]

Y = 
 [[ 2  3  4]
 [ 7  8  9]
 [12 13 14]]

v =  [10 11 12 13 14]

q =  [ 2  7 12 17]

R = 
 [[ 2]
 [ 7]
 [12]
 [17]]


## 2. Slicing and editing elements in a 2-D ndarray

In [5]:
# We create a 4 x 5 ndarray that contains integers from 0 to 19
X = np.arange(20).reshape(4, 5)

# We print X
print()
print('X = \n', X)
print()

# We select all the elements that are in the 2nd through 4th rows and in the 3rd to 4th columns
Z = X[1:4,2:5]

# We print Z
print()
print('Z = \n', Z)
print()

# We change the last element in Z to 555
Z[2,2] = 555

# We print X
print()
print('X = \n', X)
print()


X = 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


Z = 
 [[ 7  8  9]
 [12 13 14]
 [17 18 19]]


X = 
 [[  0   1   2   3   4]
 [  5   6   7   8   9]
 [ 10  11  12  13  14]
 [ 15  16  17  18 555]]



## 3. Demonstrate the copy() function
`ndarray.copy(order='C')`

In [8]:
# We create a 4 x 5 ndarray that contains integers from 0 to 19
X = np.arange(20).reshape(4, 5)

# We print X
print()
print('X = \n', X)
print()

# create a copy of the slice using the np.copy() function
Z = np.copy(X[1:4,2:5])

#  create a copy of the slice using the copy as a method
W = X[1:4,2:5].copy()

# We change the last element in Z to 555
Z[2,2] = 555

# We change the last element in W to 444
W[2,2] = 444

# We print X
print()
print('X = \n', X)

# We print Z
print()
print('Z = \n', Z)

# We print W
print()
print('W = \n', W)


X = 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


X = 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]

Z = 
 [[  7   8   9]
 [ 12  13  14]
 [ 17  18 555]]

W = 
 [[  7   8   9]
 [ 12  13  14]
 [ 17  18 444]]


## 4 a. Use an array as indices to either make slices, select, or change elements

In [9]:
# We create a 4 x 5 ndarray that contains integers from 0 to 19
X = np.arange(20).reshape(4, 5)

# We create a rank 1 ndarray that will serve as indices to select elements from X
indices = np.array([1,3])

# We print X
print()
print('X = \n', X)
print()

# We print indices
print('indices = ', indices)
print()

# We use the indices ndarray to select the 2nd and 4th row of X
Y = X[indices,:]

# We use the indices ndarray to select the 2nd and 4th column of X
Z = X[:, indices]

# We print Y
print()
print('Y = \n', Y)

# We print Z
print()
print('Z = \n', Z)


X = 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]

indices =  [1 3]


Y = 
 [[ 5  6  7  8  9]
 [15 16 17 18 19]]

Z = 
 [[ 1  3]
 [ 6  8]
 [11 13]
 [16 18]]


## 4 b. Use an array as indices to extract specific rows from a rank 2 ndarray.

In [18]:
X = np.random.randint(1,20, size=(50,5))
print("Shape of X is: ", X.shape)
print(X, '\n')

# Create a rank 1 ndarray that contains a randomly chosen 10 values between `0` to `len(X)` (50)
# The row_indices would represent the indices of rows of X
row_indices = np.random.randint(0,50, size=10)
print("Random 10 indices are: ", row_indices, '\n')

# To Do 1 - Print those rows of X whose indices are represented by entire row_indices ndarray
# Hint - Use the row_indices ndarray to select specified rows of X
X_subset = X[row_indices, :]
print(X_subset, '\n')

# To Do 2 - Print those rows of X whose indices are present in row_indices[4:8]
X_subset = X[row_indices[4:8], :]
print(X_subset, '\n')

Shape of X is:  (50, 5)
[[ 5  2  9  2 10]
 [14 12 10 11 18]
 [19 11  2  6 18]
 [15 10  6  7 19]
 [11 12  8  4  4]
 [ 8  6 16  5  8]
 [11  6 19 10 17]
 [11  2 11  5  5]
 [10  2 14  2  6]
 [ 6 16  3  3 19]
 [12  9  2 13 14]
 [18 13 12  1  6]
 [ 9 12  5 17 11]
 [ 9 17  7 12 16]
 [12 15 11  5 12]
 [ 8 11  8 19  6]
 [ 4  3 19 16 12]
 [ 3  4  6 15  6]
 [ 8  6  8 11  2]
 [14  4  2  4 17]
 [ 3  1  3  4 11]
 [10 19  3 17 11]
 [ 8 18  1 13  4]
 [ 7  5  8 15  7]
 [12  2  4 16 15]
 [ 2 16  5  9  6]
 [18 10  2  7 14]
 [ 2  9  6  7 12]
 [10  2 17 14 18]
 [10  1 13 19  3]
 [ 2 11 15 13  2]
 [ 5  2  2 14 18]
 [ 5 11 19 16 19]
 [ 8 19  6 19 17]
 [10 12  5 14  3]
 [ 2  3  6 19  5]
 [16 16 17  2  3]
 [ 3 15 19 19  6]
 [16 19 13 11 11]
 [11  5  1  7  9]
 [13 17  1  5 19]
 [ 3  6 11  4  5]
 [19  5  2 17 17]
 [ 5 11 17 14 16]
 [13 11  6 16 18]
 [14 11  4 13 10]
 [12 19  1 14  9]
 [ 4 15 14  9 18]
 [18  8 14  7  2]
 [ 1 17 12 17 19]] 

Random 10 indices are:  [ 1 28 35 26 10 42 23 42 38 10] 

[[14 12 10 11 1

## Demonstrate the diag() function
`numpy.diag(array, k=0)`

In [19]:
# We create a 5 x 5 ndarray that contains integers from 0 to 24
X = np.arange(25).reshape(5, 5)

# We print X
print()
print('X = \n', X)
print()

# We print the elements in the main diagonal of X
print('z =', np.diag(X))
print()

# We print the elements above the main diagonal of X
print('y =', np.diag(X, k=1))
print()

# We print the elements below the main diagonal of X
print('w = ', np.diag(X, k=-1))


X = 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

z = [ 0  6 12 18 24]

y = [ 1  7 13 19]

w =  [ 5 11 17 23]


## 6. Demonstrate the unique() function
`numpy.unique(array, return_index=False, return_inverse=False, return_counts=False, axis=None)`

In [20]:
# Create 3 x 3 ndarray with repeated values
X = np.array([[1,2,3],[5,2,8],[1,2,3]])

# We print X
print()
print('X = \n', X)
print()

# We print the unique elements of X 
print('The unique elements in X are:',np.unique(X))


X = 
 [[1 2 3]
 [5 2 8]
 [1 2 3]]

The unique elements in X are: [1 2 3 5 8]
