## 1. Boolean indexing

In [2]:
import numpy as np
# We create a 5 x 5 ndarray that contains integers from 0 to 24
X = np.arange(25).reshape(5, 5)

# We print X
print()
print('Original X = \n', X)
print()

# We use Boolean indexing to select elements in X:
print('The elements in X that are greater than 10:', X[X > 10])
print('The elements in X that less than or equal to 7:', X[X <= 7])
print('The elements in X that are between 10 and 17:', X[(X > 10) & (X < 17)])

# We use Boolean indexing to assign the elements that are between 10 and 17 the value of -1
X[(X > 10) & (X < 17)] = -1

# We print X
print()
print('X = \n', X)
print()


Original X = 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

The elements in X that are greater than 10: [11 12 13 14 15 16 17 18 19 20 21 22 23 24]
The elements in X that less than or equal to 7: [0 1 2 3 4 5 6 7]
The elements in X that are between 10 and 17: [11 12 13 14 15 16]

X = 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 -1 -1 -1 -1]
 [-1 -1 17 18 19]
 [20 21 22 23 24]]



## 2. Set operations (union, difference, intersection)

In [3]:
# We create a rank 1 ndarray
x = np.array([1,2,3,4,5])

# We create a rank 1 ndarray
y = np.array([6,7,2,8,4])

# We print x
print()
print('x = ', x)

# We print y
print()
print('y = ', y)

# We use set operations to compare x and y:
print()
print('The elements that are both in x and y:', np.intersect1d(x,y))
print('The elements that are in x that are not in y:', np.setdiff1d(x,y))
print('All the elements of x and y:',np.union1d(x,y))


x =  [1 2 3 4 5]

y =  [6 7 2 8 4]

The elements that are both in x and y: [2 4]
The elements that are in x that are not in y: [1 3 5]
All the elements of x and y: [1 2 3 4 5 6 7 8]


## 3. Sort arrays using sort() function
`ndarray.sort(axis=-1, kind=None, order=None)`

In [4]:
# We create an unsorted rank 1 ndarray
x = np.random.randint(1,11,size=(10,))

# We print x
print()
print('Original x = ', x)

# We sort x and print the sorted array using sort as a function.
print()
print('Sorted x (out of place):', np.sort(x))

# When we sort out of place the original array remains intact. To see this we print x again
print()
print('x after sorting:', x)


Original x =  [ 1  3  8 10  7  2  8  6  3  4]

Sorted x (out of place): [ 1  2  3  3  4  6  7  8  8 10]

x after sorting: [ 1  3  8 10  7  2  8  6  3  4]


Notice that np.sort() sorts the array but, if the ndarray being sorted has repeated values, np.sort() leaves those values in the sorted array. However, if desired, we can use the unique() function. Let's see how we can sort the unique elements of x above:



In [5]:
# Returns the sorted unique elements of an array
print(np.unique(x))

[ 1  2  3  4  6  7  8 10]


## 4. Sort rank-1 arrays using sort() method

In [6]:
# We create an unsorted rank 1 ndarray
x = np.random.randint(1,11,size=(10,))

# We print x
print()
print('Original x = ', x)

# We sort x and print the sorted array using sort as a method.
x.sort()

# When we sort in place the original array is changed to the sorted array. To see this we print x again
print()
print('x after sorting:', x)


Original x =  [ 6 10  3 10  9  6 10  9  9  7]

x after sorting: [ 3  6  6  7  9  9  9 10 10 10]


## 5. Sort rank-2 arrays by specific axis.
`numpy.sort(array, axis=-1, kind=None, order=None)`
- If nothing is specified, the default value is `axis = -1`, which sorts along the last axis. In the case of a given 2-D ndarray, the last axis value is 1.
- If explicitly `axis = None` is specified, the array is flattened before sorting. It will return a 1-D array.
- If `axis = 0` is specified for a given 2-D array - For one column at a time, the function will sort all rows, without disturbing other elements. In the final output, you will see that each column has been sorted individually.
- The output of `axis = 1` for a given 2-D array is vice-versa for axis = 0. In the final output, you will see that each row has been sorted individually.

In [7]:
# We create an unsorted rank 2 ndarray
X = np.random.randint(1,11,size=(5,5))

# We print X
print()
print('Original X = \n', X)
print()

# We sort the columns of X and print the sorted array
print()
print('X with sorted columns :\n', np.sort(X, axis = 0))

# We sort the rows of X and print the sorted array
print()
print('X with sorted rows :\n', np.sort(X, axis = 1))


Original X = 
 [[ 9  1 10  1  5]
 [ 7 10 10  2  7]
 [ 7  3  5  5  6]
 [ 9 10  7  2  6]
 [ 7 10  2  5  8]]


X with sorted columns :
 [[ 7  1  2  1  5]
 [ 7  3  5  2  6]
 [ 7 10  7  2  6]
 [ 9 10 10  5  7]
 [ 9 10 10  5  8]]

X with sorted rows :
 [[ 1  1  5  9 10]
 [ 2  7  7 10 10]
 [ 3  5  5  6  7]
 [ 2  6  7  9 10]
 [ 2  5  7  8 10]]
